name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Optional test (uncomment if needed)
      # - name: Test SSH Connection
      #   run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo ✅ SSH connection successful"

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/storivita.com
            # Remove everything inside but keep the folder
            rm -rf ./* .[^.] .??*
            
            # Fresh clone
            git clone git@github.com:AbbasMhowwala35/storivita.git /var/www/storivita.com
            
            cd /var/www/storivita.com
            npm install --production
            npm run build
            pm2 restart all
          EOF

